[functions]
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**", "middleware/is-logged-in.js", "middleware/pass-user-to-view.js"]

# Allow direct access to static images
[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200

# Catch-all redirect for API calls
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
 